name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: 'ca-central-1'  # Your AWS region
  EB_APPLICATION_NAME: 'backendautomation-env'  # Replace with your EB app name
  EB_ENVIRONMENT_NAME: 'backendautomation-env'  # Replace with your EB environment name
  S3_BUCKET: 'elasticbeanstalk-ca-central-1-342097064907'  # Your existing bucket

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build with Maven
      run: mvn clean package
      
    - name: Create deployment package
      run: |
        mkdir -p deploy
        cp target/*.jar deploy/application.jar
        cp Procfile deploy/
        cd deploy && zip -r ../target/application.zip ./*
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Upload to S3
      run: |
        aws s3 cp target/application.zip s3://${{ env.S3_BUCKET }}/${{ github.sha }}.zip
        
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        version_label: ${{ github.sha }}
        region: ${{ env.AWS_REGION }}
        existing_bucket_name: ${{ env.S3_BUCKET }}
        deployment_package: target/application.zip
        wait_for_environment_recovery: 30
